development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: randompocket_development
  pool: 5
  username: randompocket
  password: randompocket
  socket: /opt/local/var/run/mysql5/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: randompocket_test
  pool: 5
  username: randompocket
  password: randompocket
  socket: /opt/local/var/run/mysql5/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: randompocket_production
  pool: 5
  username: root
  password:
  socket: /opt/local/var/run/mysql5/mysqld.sock
